#FROM resin/rpi-raspbian:stretch as bazel-builder

FROM ubuntu as bazel-builder
ADD setup.sh /
RUN bash /setup.sh

# https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds
FROM ubuntu
COPY --from=bazel-builder \
  /usr/local/bin/protoc \
  /bazel/bazel-bin/blaze \
  /bazel/third_party/grpc/compiler/src/java_plugin/cpp/protoc-gen-grpc-java \
  /usr/bin
